#!/bin/bash -e
#PBS -l walltime=8:00:00,nodes=1:ppn=1,mem=2gb
#PBS -q blekhman
#PBS -m a
#PBS -M rabdill@umn.edu
#PBS -N ${PROJECT}download

# This script expects a directory matching the project name
# to be present at ~/shithouse/accession_lists/
# with a file in it called "SraAccList.txt" listing all the samples
# to be downloaded from SRA.
echo "${PROJECT},download,start" >> ~/shithouse/activity.csv

mv ~/shithouse/accession_lists/${PROJECT} /scratch.global/rabdill/bulk/
cd /scratch.global/rabdill/bulk/${PROJECT}
mkdir fastq

#module load aspera
module load sratoolkit # currently 2.8.2

# configuration: vdb-config -i

# find a list of samples, pick one, then go to
# the PROJECT page for it. Click on "SRA Experiments"
# and then export all the accession numbers to a file
# called SraAccList.txt

prefetch --option-file SraAccList.txt

for sample in $(cat SraAccList.txt)
do
    echo "On sample: $sample"
    fastq-dump -I --split-files $sample -O /scratch.global/rabdill/bulk/${PROJECT}/fastq
done

# create a "samples" file listing ONLY the samples that were successfully processed
cd fastq
ls *_1.fastq | cut -f1 -d "_" > ../samples.txt
echo "DONE. Submitting trimming job."
echo "${PROJECT},download,end" >> ~/shithouse/activity.csv

cd ~/shithouse/logs
qsub ../code/run_shi7.pbs -v PROJECT=${PROJECT}
