#!/bin/bash -e
#PBS -l walltime=16:00:00,nodes=1:ppn=8,mem=16gb 
#PBS -q blekhman
#PBS -m abe 
#PBS -M rabdill@umn.edu
#PBS -N ${PROJECT}trim

echo "${PROJECT},trim,start" >> ~/shithouse/activity.csv

mkdir /scratch.global/rabdill/bulk/${PROJECT}/results
mkdir /scratch.global/rabdill/bulk/${PROJECT}/trimmed # for shi7
mkdir /scratch.global/rabdill/bulk/${PROJECT}/intermediate # for dada2
mkdir /scratch.global/rabdill/bulk/${PROJECT}/temp

# record read lengths
echo "Assessing read length..."
for filename in /scratch.global/rabdill/bulk/${PROJECT}/fastq/*.fastq; do
    [ -e "$filename" ] || continue # make sure something matches
    cat $filename | perl -ne '$s=<>;<>;<>;chomp($s);print length($s)."\n";' >> /scratch.global/rabdill/bulk/${PROJECT}/temp/readlength.raw.txt
done
cat /scratch.global/rabdill/bulk/${PROJECT}/temp/readlength.raw.txt | uniq -c >> /scratch.global/rabdill/bulk/${PROJECT}/results/readlength.txt

# TRIMMING with shi7
# (all this weird formatting is because we have to run shi7 SPECIFICALLY
#  with python 2, rather than the python 3 that the system defaults to, 
#  because of an outstanding bug)
cd ~/shithouse/shi7_0.9.9/
echo "Learning shi7 parameters..."
python2 shi7_learning.py -i /scratch.global/rabdill/bulk/${PROJECT}/fastq -o /scratch.global/rabdill/bulk/${PROJECT}/learnt

a=$(cat /scratch.global/rabdill/bulk/${PROJECT}/learnt/shi7_cmd.sh)

$(echo python2 $a --flash False --convert_fasta False --combine_fasta False --output /scratch.global/rabdill/bulk/${PROJECT}/trimmed)

echo "DONE. Starting DADA2 run."
echo "${PROJECT},trim,end" >> ~/shithouse/activity.csv

cd ~/shithouse/logs
qsub ../code/run_dada.pbs -v PROJECT=${PROJECT}
